grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false 
  module_2:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false 
  module_3:
    class: ElasticNet
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false          
  module_4:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
